### ISSUE TITLE
Bottom edge of window truncated

### ISSUE THREAD

**Issue by JohnLGalt** [timche/gmail-desktop#279] opened 2021-04-28 14:39 UTC
**OS**
Windows 10 x64 20H2 (19042.928)

**Gmail Desktop Version**
v3.0.0 αlpha 27

(Hardware as follows:  https://valid.x86.fr/tf5prr )

**Describe the bug**
If I maximize the window (or go full screen) the bottom of the window gets truncated off screen - regardless of whether I have autohide taskbar enabled or disabled.

**Steps to reproduce the behavior**
1. Click on Maximize button
2. See error

**Expected behavior**
The entire GMail window is visible in the app

**Media**
With taskbar always showing

![Bottom truncated 01](https://user-images.githubusercontent.com/7432512/116421962-4de7a500-a80d-11eb-84ea-d66aab0712ff.png)

With taskbar auto hidden

![Bottom truncated 02](https://user-images.githubusercontent.com/7432512/116422009-563fe000-a80d-11eb-8518-80313d0092e0.png)

**Additional context**
I've tried changing numerous items in the preferences, including:

- Compact Header
- Hide Footer 
- Hide Support
- Hide Menu Bar
- Adblocker settings

And more - nothing makes the bottom edge visible.

Please let me know if I need to supply more information.

**Comment by JohnLGalt** [comment] 2021-05-09 15:48
My current workaround is to not use the window maximized (using Windows controls) but to then size the window manually so it takes up the appropriate amount of real estate on my screen.

In the meantime, I've got 6 accounts working in it, each with a different (and usually custom) theme, and the app is only using ~ 760 MB.  Kudos, devs - this is a winner and a keeper, for sure.

**Comment by JohnLGalt** [comment] 2022-02-12 14:21
I didn't even see 31, still only have 30. I'll grab it later today and let
you know.

You've been kicking out some serious updates, kudos!

**Comment by timche** [comment] 2022-02-12 14:28
In case you don't know yet, you can manually check for updates:

![image](https://user-images.githubusercontent.com/8075074/153715230-cd70cec9-bfc8-48de-b36e-d5fea900a7c6.png)

It seems to work fine for me now:

![image](https://user-images.githubusercontent.com/8075074/153715278-99a2fa45-f871-4c30-8c39-03faec995d73.png)

**Comment by timche** [comment] 2022-02-12 15:12
I'll close this issue as I can't reproduce it anymore. If you still have it @JohnLGalt, I'll re-open it.

**Closed by timche** 2022-02-12 15:12 UTC
Labels: bug, windows
